/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import java.awt.Component;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author David B
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();

        this.setLocationRelativeTo(null);
    }
    
    private void hideEveryPanelExceptThis(JPanel panel, boolean ... flagCleanPanel){
        boolean flagrResponseClean = (flagCleanPanel.length >= 1) ? flagCleanPanel[0] : false;
        
        for(Component component : LayerPn.getComponents()) 
            if(component instanceof JPanel)
                component.setVisible(false);
        
        if(flagrResponseClean) cleanWindow(panel);
        
        panel.setVisible(true);
    }
     
     private void cleanWindow(JPanel panel){
        for(Component component : panel.getComponents()){   
            if(component instanceof JTextField){
                JTextField comp = (JTextField) component;
                comp.setText("");
            }
            else if (component instanceof JComboBox){
                JComboBox comp = (JComboBox) component;
                comp.setSelectedIndex(0);
            }
            else if(component instanceof JFormattedTextField){
                JFormattedTextField comp = (JFormattedTextField) component;
                comp.setText("");
            }
            else if(component instanceof JTextField){
                JTextField comp = (JTextField) component;
                comp.setText("");
            }
            else if(component instanceof JTextArea){
                JTextArea comp = (JTextArea) component;
                comp.setText("");
            }
            else if(component instanceof JTable){
                JTable comp = (JTable) component;
                comp.removeAll();
            }
        }
    }
     
    private int closeProgram(){
        confirmExit.setVisible(true);
        LayerPn.setVisible(false);
        return 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmExit = new javax.swing.JDialog();
        cofirmExit_label_tittle = new javax.swing.JLabel();
        cofirmExit_button_Accept = new javax.swing.JButton();
        cofirmExit_button_Cancel = new javax.swing.JButton();
        LogIn = new javax.swing.JFrame();
        LogIn_MainPanel = new javax.swing.JPanel();
        LogIn_Header = new javax.swing.JPanel();
        LogIn_logo01 = new javax.swing.JLabel();
        LogIn_Logo02 = new javax.swing.JLabel();
        LogIn_TextField_UserName = new javax.swing.JTextField();
        LogIn_Label_UserName = new javax.swing.JLabel();
        LogIn_Label_Password = new javax.swing.JLabel();
        LogIn_PasswordField_Password = new javax.swing.JPasswordField();
        LogIn_Button_SignUp = new javax.swing.JButton();
        LogIn_Button_Accept = new javax.swing.JButton();
        LogIn_Button_PasswordRecovery = new javax.swing.JButton();
        LogIn_Label_PasswordRecovery = new javax.swing.JLabel();
        SignUp = new javax.swing.JFrame();
        SignUp_MainPanel = new javax.swing.JPanel();
        SignUp_Header = new javax.swing.JPanel();
        SignUp_Logo2 = new javax.swing.JLabel();
        SignUp_Label_Tittle = new javax.swing.JLabel();
        SignUp_TextField_2ndSurname = new javax.swing.JTextField();
        SignUp_Label_Username = new javax.swing.JLabel();
        SignUp_Button_Cancel = new javax.swing.JButton();
        SignUp_Button_Accept = new javax.swing.JButton();
        SignUp_TextField_Username = new javax.swing.JTextField();
        SignUp_Label_MiddleName = new javax.swing.JLabel();
        SignUp_TextField_MiddleName = new javax.swing.JTextField();
        SignUp_Label_1stSurname = new javax.swing.JLabel();
        SignUp_TextField_1stSurname = new javax.swing.JTextField();
        SignUp_Label_Direction = new javax.swing.JLabel();
        SignUp_Label_2ndSurname = new javax.swing.JLabel();
        SignUp_FormattedTextField_Password = new javax.swing.JFormattedTextField();
        SignUp_Label_BirthDate = new javax.swing.JLabel();
        SignUp_Button_Address = new javax.swing.JButton();
        SignUp_Label_Password = new javax.swing.JLabel();
        SignUp_Button_ChooseAPhoto = new javax.swing.JButton();
        LogIn_LabelPassword8 = new javax.swing.JLabel();
        SignUp_Label_FirstName = new javax.swing.JLabel();
        SignUp_TextField_FirstName = new javax.swing.JTextField();
        SignUp_Label_Email = new javax.swing.JLabel();
        SignUp_FormattedTextField_Email = new javax.swing.JFormattedTextField();
        SignUp_FormattedTextField_BirthDate1 = new javax.swing.JFormattedTextField();
        PasswordRecovery = new javax.swing.JFrame();
        PasswordRecovery_MainPanel = new javax.swing.JPanel();
        PasswordRecovery_Header = new javax.swing.JPanel();
        PasswordRecovery_logo2 = new javax.swing.JLabel();
        PasswordRecovery_Label_Tittle = new javax.swing.JLabel();
        PasswordRecovery_TextField_UserName1 = new javax.swing.JTextField();
        PasswordRecovery_Label_UserName = new javax.swing.JLabel();
        PasswordRecovery_Button_Cancel = new javax.swing.JButton();
        PasswordRecovery_Button_Accept = new javax.swing.JButton();
        LayerPn = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();

        confirmExit.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        confirmExit.setMaximumSize(new java.awt.Dimension(400, 207));
        confirmExit.setMinimumSize(new java.awt.Dimension(400, 207));

        cofirmExit_label_tittle.setFont(new java.awt.Font("Kozuka Mincho Pro L", 0, 24)); // NOI18N
        cofirmExit_label_tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cofirmExit_label_tittle.setText("Do you want to close the program?");

        cofirmExit_button_Accept.setText("Accept");
        cofirmExit_button_Accept.setMaximumSize(new java.awt.Dimension(90, 30));
        cofirmExit_button_Accept.setMinimumSize(new java.awt.Dimension(90, 30));
        cofirmExit_button_Accept.setPreferredSize(new java.awt.Dimension(90, 30));
        cofirmExit_button_Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cofirmExit_button_AcceptActionPerformed(evt);
            }
        });

        cofirmExit_button_Cancel.setText("Cancel");
        cofirmExit_button_Cancel.setMaximumSize(new java.awt.Dimension(90, 30));
        cofirmExit_button_Cancel.setMinimumSize(new java.awt.Dimension(90, 30));
        cofirmExit_button_Cancel.setPreferredSize(new java.awt.Dimension(90, 30));
        cofirmExit_button_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cofirmExit_button_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout confirmExitLayout = new javax.swing.GroupLayout(confirmExit.getContentPane());
        confirmExit.getContentPane().setLayout(confirmExitLayout);
        confirmExitLayout.setHorizontalGroup(
            confirmExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, confirmExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cofirmExit_label_tittle, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(confirmExitLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(cofirmExit_button_Accept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(cofirmExit_button_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        confirmExitLayout.setVerticalGroup(
            confirmExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmExitLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cofirmExit_label_tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(confirmExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cofirmExit_button_Accept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cofirmExit_button_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        LogIn.setAlwaysOnTop(true);
        LogIn.setAutoRequestFocus(false);
        LogIn.setBackground(new java.awt.Color(255, 180, 162));
        LogIn.setMaximumSize(new java.awt.Dimension(600, 450));
        LogIn.setMinimumSize(new java.awt.Dimension(600, 450));
        LogIn.setUndecorated(true);
        LogIn.setPreferredSize(new java.awt.Dimension(600, 450));

        LogIn_MainPanel.setBackground(new java.awt.Color(109, 104, 117));
        LogIn_MainPanel.setToolTipText("");
        LogIn_MainPanel.setMaximumSize(new java.awt.Dimension(600, 420));
        LogIn_MainPanel.setMinimumSize(new java.awt.Dimension(600, 420));
        LogIn_MainPanel.setName(""); // NOI18N
        LogIn_MainPanel.setPreferredSize(new java.awt.Dimension(600, 420));
        LogIn_MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogIn_Header.setBackground(new java.awt.Color(255, 180, 162));
        LogIn_Header.setMaximumSize(new java.awt.Dimension(600, 150));
        LogIn_Header.setMinimumSize(new java.awt.Dimension(600, 150));
        LogIn_Header.setPreferredSize(new java.awt.Dimension(600, 150));

        LogIn_logo01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo BD_1.png"))); // NOI18N

        LogIn_Logo02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo BD_2.png"))); // NOI18N

        javax.swing.GroupLayout LogIn_HeaderLayout = new javax.swing.GroupLayout(LogIn_Header);
        LogIn_Header.setLayout(LogIn_HeaderLayout);
        LogIn_HeaderLayout.setHorizontalGroup(
            LogIn_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogIn_HeaderLayout.createSequentialGroup()
                .addComponent(LogIn_logo01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(LogIn_Logo02)
                .addGap(28, 28, 28))
        );
        LogIn_HeaderLayout.setVerticalGroup(
            LogIn_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogIn_logo01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogIn_Logo02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        LogIn_MainPanel.add(LogIn_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        LogIn_TextField_UserName.setMaximumSize(new java.awt.Dimension(90, 30));
        LogIn_TextField_UserName.setMinimumSize(new java.awt.Dimension(90, 30));
        LogIn_TextField_UserName.setPreferredSize(new java.awt.Dimension(90, 30));
        LogIn_TextField_UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogIn_TextField_UserNameActionPerformed(evt);
            }
        });
        LogIn_MainPanel.add(LogIn_TextField_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 218, 260, -1));

        LogIn_Label_UserName.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 24)); // NOI18N
        LogIn_Label_UserName.setForeground(new java.awt.Color(255, 255, 255));
        LogIn_Label_UserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogIn_Label_UserName.setText("Username:");
        LogIn_Label_UserName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        LogIn_MainPanel.add(LogIn_Label_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 215, 148, 30));

        LogIn_Label_Password.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 24)); // NOI18N
        LogIn_Label_Password.setForeground(new java.awt.Color(255, 255, 255));
        LogIn_Label_Password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogIn_Label_Password.setText("Password:");
        LogIn_Label_Password.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        LogIn_MainPanel.add(LogIn_Label_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 266, 148, 30));

        LogIn_PasswordField_Password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        LogIn_MainPanel.add(LogIn_PasswordField_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 266, 260, 30));

        LogIn_Button_SignUp.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 18)); // NOI18N
        LogIn_Button_SignUp.setText("Sign up ");
        LogIn_Button_SignUp.setAlignmentY(0.0F);
        LogIn_Button_SignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogIn_Button_SignUp.setFocusCycleRoot(true);
        LogIn_Button_SignUp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LogIn_Button_SignUp.setIconTextGap(0);
        LogIn_Button_SignUp.setMaximumSize(new java.awt.Dimension(90, 30));
        LogIn_Button_SignUp.setMinimumSize(new java.awt.Dimension(90, 30));
        LogIn_Button_SignUp.setPreferredSize(new java.awt.Dimension(90, 30));
        LogIn_Button_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogIn_Button_SignUpActionPerformed(evt);
            }
        });
        LogIn_MainPanel.add(LogIn_Button_SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 110, 40));

        LogIn_Button_Accept.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 18)); // NOI18N
        LogIn_Button_Accept.setText("Accept");
        LogIn_Button_Accept.setAlignmentY(0.0F);
        LogIn_Button_Accept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogIn_Button_Accept.setFocusCycleRoot(true);
        LogIn_Button_Accept.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LogIn_Button_Accept.setIconTextGap(0);
        LogIn_Button_Accept.setMaximumSize(new java.awt.Dimension(90, 30));
        LogIn_Button_Accept.setMinimumSize(new java.awt.Dimension(90, 30));
        LogIn_Button_Accept.setPreferredSize(new java.awt.Dimension(90, 30));
        LogIn_Button_Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogIn_Button_AcceptActionPerformed(evt);
            }
        });
        LogIn_MainPanel.add(LogIn_Button_Accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 110, 40));

        LogIn_Button_PasswordRecovery.setBorderPainted(false);
        LogIn_Button_PasswordRecovery.setContentAreaFilled(false);
        LogIn_Button_PasswordRecovery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogIn_Button_PasswordRecovery.setFocusPainted(false);
        LogIn_Button_PasswordRecovery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogIn_Button_PasswordRecoveryActionPerformed(evt);
            }
        });
        LogIn_MainPanel.add(LogIn_Button_PasswordRecovery, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 160, 20));

        LogIn_Label_PasswordRecovery.setFont(new java.awt.Font("Kozuka Mincho Pro L", 2, 14)); // NOI18N
        LogIn_Label_PasswordRecovery.setForeground(new java.awt.Color(204, 204, 204));
        LogIn_Label_PasswordRecovery.setText("Password Recovery");
        LogIn_Label_PasswordRecovery.setToolTipText("");
        LogIn_Label_PasswordRecovery.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        LogIn_Label_PasswordRecovery.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LogIn_MainPanel.add(LogIn_Label_PasswordRecovery, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 170, 20));

        javax.swing.GroupLayout LogInLayout = new javax.swing.GroupLayout(LogIn.getContentPane());
        LogIn.getContentPane().setLayout(LogInLayout);
        LogInLayout.setHorizontalGroup(
            LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogIn_MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        LogInLayout.setVerticalGroup(
            LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogIn_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        SignUp.setAlwaysOnTop(true);
        SignUp.setAutoRequestFocus(false);
        SignUp.setBackground(new java.awt.Color(255, 180, 162));
        SignUp.setMinimumSize(new java.awt.Dimension(600, 450));
        SignUp.setUndecorated(true);

        SignUp_MainPanel.setBackground(new java.awt.Color(109, 104, 117));
        SignUp_MainPanel.setToolTipText("");
        SignUp_MainPanel.setMaximumSize(new java.awt.Dimension(676, 420));
        SignUp_MainPanel.setMinimumSize(new java.awt.Dimension(676, 420));
        SignUp_MainPanel.setName(""); // NOI18N
        SignUp_MainPanel.setPreferredSize(new java.awt.Dimension(676, 420));
        SignUp_MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignUp_Header.setBackground(new java.awt.Color(255, 180, 162));
        SignUp_Header.setMaximumSize(new java.awt.Dimension(600, 150));
        SignUp_Header.setMinimumSize(new java.awt.Dimension(600, 150));

        SignUp_Logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo BD_2_50p.png"))); // NOI18N

        SignUp_Label_Tittle.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 2, 48)); // NOI18N
        SignUp_Label_Tittle.setForeground(new java.awt.Color(90, 87, 96));
        SignUp_Label_Tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUp_Label_Tittle.setText("Sign Up");
        SignUp_Label_Tittle.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout SignUp_HeaderLayout = new javax.swing.GroupLayout(SignUp_Header);
        SignUp_Header.setLayout(SignUp_HeaderLayout);
        SignUp_HeaderLayout.setHorizontalGroup(
            SignUp_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUp_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SignUp_Logo2)
                .addGap(80, 80, 80)
                .addComponent(SignUp_Label_Tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        SignUp_HeaderLayout.setVerticalGroup(
            SignUp_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUp_HeaderLayout.createSequentialGroup()
                .addGroup(SignUp_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SignUp_Logo2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(SignUp_Label_Tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 90, Short.MAX_VALUE))
        );

        SignUp_MainPanel.add(SignUp_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 60));

        SignUp_TextField_2ndSurname.setMaximumSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_2ndSurname.setMinimumSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_2ndSurname.setPreferredSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_2ndSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_TextField_2ndSurnameActionPerformed(evt);
            }
        });
        SignUp_MainPanel.add(SignUp_TextField_2ndSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 170, -1));

        SignUp_Label_Username.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 18)); // NOI18N
        SignUp_Label_Username.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_Label_Username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SignUp_Label_Username.setText("Username");
        SignUp_Label_Username.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SignUp_MainPanel.add(SignUp_Label_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 120, 20));

        SignUp_Button_Cancel.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 18)); // NOI18N
        SignUp_Button_Cancel.setText("Sign up ");
        SignUp_Button_Cancel.setAlignmentY(0.0F);
        SignUp_Button_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUp_Button_Cancel.setFocusCycleRoot(true);
        SignUp_Button_Cancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SignUp_Button_Cancel.setIconTextGap(0);
        SignUp_Button_Cancel.setMaximumSize(new java.awt.Dimension(90, 30));
        SignUp_Button_Cancel.setMinimumSize(new java.awt.Dimension(90, 30));
        SignUp_Button_Cancel.setPreferredSize(new java.awt.Dimension(90, 30));
        SignUp_Button_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_Button_CancelActionPerformed(evt);
            }
        });
        SignUp_MainPanel.add(SignUp_Button_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 110, 40));

        SignUp_Button_Accept.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 18)); // NOI18N
        SignUp_Button_Accept.setText("Accept");
        SignUp_Button_Accept.setAlignmentY(0.0F);
        SignUp_Button_Accept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUp_Button_Accept.setFocusCycleRoot(true);
        SignUp_Button_Accept.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SignUp_Button_Accept.setIconTextGap(0);
        SignUp_Button_Accept.setMaximumSize(new java.awt.Dimension(90, 30));
        SignUp_Button_Accept.setMinimumSize(new java.awt.Dimension(90, 30));
        SignUp_Button_Accept.setPreferredSize(new java.awt.Dimension(90, 30));
        SignUp_Button_Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_Button_AcceptActionPerformed(evt);
            }
        });
        SignUp_MainPanel.add(SignUp_Button_Accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 110, 40));

        SignUp_TextField_Username.setMaximumSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_Username.setMinimumSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_Username.setPreferredSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_TextField_UsernameActionPerformed(evt);
            }
        });
        SignUp_MainPanel.add(SignUp_TextField_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 170, 30));

        SignUp_Label_MiddleName.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 18)); // NOI18N
        SignUp_Label_MiddleName.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_Label_MiddleName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SignUp_Label_MiddleName.setText("Middle name:");
        SignUp_Label_MiddleName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SignUp_MainPanel.add(SignUp_Label_MiddleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 120, 20));

        SignUp_TextField_MiddleName.setMaximumSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_MiddleName.setMinimumSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_MiddleName.setPreferredSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_MiddleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_TextField_MiddleNameActionPerformed(evt);
            }
        });
        SignUp_MainPanel.add(SignUp_TextField_MiddleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 170, -1));

        SignUp_Label_1stSurname.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 18)); // NOI18N
        SignUp_Label_1stSurname.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_Label_1stSurname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SignUp_Label_1stSurname.setText("1st Surname:");
        SignUp_Label_1stSurname.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SignUp_MainPanel.add(SignUp_Label_1stSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 120, 20));

        SignUp_TextField_1stSurname.setMaximumSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_1stSurname.setMinimumSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_1stSurname.setPreferredSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_1stSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_TextField_1stSurnameActionPerformed(evt);
            }
        });
        SignUp_MainPanel.add(SignUp_TextField_1stSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 170, 30));

        SignUp_Label_Direction.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 18)); // NOI18N
        SignUp_Label_Direction.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_Label_Direction.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SignUp_Label_Direction.setText("Address:");
        SignUp_Label_Direction.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SignUp_MainPanel.add(SignUp_Label_Direction, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 120, 20));

        SignUp_Label_2ndSurname.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 18)); // NOI18N
        SignUp_Label_2ndSurname.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_Label_2ndSurname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SignUp_Label_2ndSurname.setText("2nd Surname:");
        SignUp_Label_2ndSurname.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SignUp_MainPanel.add(SignUp_Label_2ndSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 120, 20));
        SignUp_MainPanel.add(SignUp_FormattedTextField_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 170, 30));

        SignUp_Label_BirthDate.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 18)); // NOI18N
        SignUp_Label_BirthDate.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_Label_BirthDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SignUp_Label_BirthDate.setText("Birth date:");
        SignUp_Label_BirthDate.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SignUp_MainPanel.add(SignUp_Label_BirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 120, 20));

        SignUp_Button_Address.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        SignUp_Button_Address.setText("Your address");
        SignUp_MainPanel.add(SignUp_Button_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 170, 30));

        SignUp_Label_Password.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 18)); // NOI18N
        SignUp_Label_Password.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_Label_Password.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SignUp_Label_Password.setText("Password");
        SignUp_Label_Password.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SignUp_MainPanel.add(SignUp_Label_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 120, 20));

        SignUp_Button_ChooseAPhoto.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        SignUp_Button_ChooseAPhoto.setText("Choose a photo");
        SignUp_MainPanel.add(SignUp_Button_ChooseAPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 170, 30));

        LogIn_LabelPassword8.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 18)); // NOI18N
        LogIn_LabelPassword8.setForeground(new java.awt.Color(255, 255, 255));
        LogIn_LabelPassword8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LogIn_LabelPassword8.setText("Photo:");
        LogIn_LabelPassword8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SignUp_MainPanel.add(LogIn_LabelPassword8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 120, 20));

        SignUp_Label_FirstName.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 18)); // NOI18N
        SignUp_Label_FirstName.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_Label_FirstName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SignUp_Label_FirstName.setText("First name:");
        SignUp_Label_FirstName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SignUp_MainPanel.add(SignUp_Label_FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 20));

        SignUp_TextField_FirstName.setMaximumSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_FirstName.setMinimumSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_FirstName.setPreferredSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_TextField_FirstNameActionPerformed(evt);
            }
        });
        SignUp_MainPanel.add(SignUp_TextField_FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 170, 30));

        SignUp_Label_Email.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 18)); // NOI18N
        SignUp_Label_Email.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_Label_Email.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SignUp_Label_Email.setText("Email:");
        SignUp_Label_Email.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SignUp_MainPanel.add(SignUp_Label_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 120, 20));
        SignUp_MainPanel.add(SignUp_FormattedTextField_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 170, 30));
        SignUp_MainPanel.add(SignUp_FormattedTextField_BirthDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 170, 30));

        javax.swing.GroupLayout SignUpLayout = new javax.swing.GroupLayout(SignUp.getContentPane());
        SignUp.getContentPane().setLayout(SignUpLayout);
        SignUpLayout.setHorizontalGroup(
            SignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignUp_MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SignUpLayout.setVerticalGroup(
            SignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignUp_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PasswordRecovery.setAlwaysOnTop(true);
        PasswordRecovery.setAutoRequestFocus(false);
        PasswordRecovery.setBackground(new java.awt.Color(255, 180, 162));
        PasswordRecovery.setMaximumSize(new java.awt.Dimension(500, 300));
        PasswordRecovery.setMinimumSize(new java.awt.Dimension(500, 300));
        PasswordRecovery.setUndecorated(true);
        PasswordRecovery.setPreferredSize(new java.awt.Dimension(500, 300));

        PasswordRecovery_MainPanel.setBackground(new java.awt.Color(109, 104, 117));
        PasswordRecovery_MainPanel.setToolTipText("");
        PasswordRecovery_MainPanel.setMaximumSize(new java.awt.Dimension(500, 300));
        PasswordRecovery_MainPanel.setMinimumSize(new java.awt.Dimension(500, 300));
        PasswordRecovery_MainPanel.setName(""); // NOI18N
        PasswordRecovery_MainPanel.setPreferredSize(new java.awt.Dimension(500, 300));
        PasswordRecovery_MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PasswordRecovery_Header.setBackground(new java.awt.Color(255, 180, 162));
        PasswordRecovery_Header.setMaximumSize(new java.awt.Dimension(600, 150));
        PasswordRecovery_Header.setMinimumSize(new java.awt.Dimension(600, 150));

        PasswordRecovery_logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo BD_1_75p.png"))); // NOI18N

        PasswordRecovery_Label_Tittle.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 2, 44)); // NOI18N
        PasswordRecovery_Label_Tittle.setForeground(new java.awt.Color(90, 87, 96));
        PasswordRecovery_Label_Tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordRecovery_Label_Tittle.setText("Password Recovery");
        PasswordRecovery_Label_Tittle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PasswordRecovery_Label_Tittle.setFocusable(false);

        javax.swing.GroupLayout PasswordRecovery_HeaderLayout = new javax.swing.GroupLayout(PasswordRecovery_Header);
        PasswordRecovery_Header.setLayout(PasswordRecovery_HeaderLayout);
        PasswordRecovery_HeaderLayout.setHorizontalGroup(
            PasswordRecovery_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasswordRecovery_HeaderLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(PasswordRecovery_logo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordRecovery_Label_Tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        PasswordRecovery_HeaderLayout.setVerticalGroup(
            PasswordRecovery_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasswordRecovery_HeaderLayout.createSequentialGroup()
                .addGroup(PasswordRecovery_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PasswordRecovery_logo2)
                    .addComponent(PasswordRecovery_Label_Tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 75, Short.MAX_VALUE))
        );

        PasswordRecovery_MainPanel.add(PasswordRecovery_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 80));

        PasswordRecovery_TextField_UserName1.setMaximumSize(new java.awt.Dimension(90, 30));
        PasswordRecovery_TextField_UserName1.setMinimumSize(new java.awt.Dimension(90, 30));
        PasswordRecovery_TextField_UserName1.setPreferredSize(new java.awt.Dimension(90, 30));
        PasswordRecovery_TextField_UserName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordRecovery_TextField_UserName1ActionPerformed(evt);
            }
        });
        PasswordRecovery_MainPanel.add(PasswordRecovery_TextField_UserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 260, -1));

        PasswordRecovery_Label_UserName.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 24)); // NOI18N
        PasswordRecovery_Label_UserName.setForeground(new java.awt.Color(255, 255, 255));
        PasswordRecovery_Label_UserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordRecovery_Label_UserName.setText("Username:");
        PasswordRecovery_Label_UserName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PasswordRecovery_Label_UserName.setFocusable(false);
        PasswordRecovery_MainPanel.add(PasswordRecovery_Label_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 148, 30));

        PasswordRecovery_Button_Cancel.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 18)); // NOI18N
        PasswordRecovery_Button_Cancel.setText("Cancel");
        PasswordRecovery_Button_Cancel.setAlignmentY(0.0F);
        PasswordRecovery_Button_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PasswordRecovery_Button_Cancel.setFocusCycleRoot(true);
        PasswordRecovery_Button_Cancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PasswordRecovery_Button_Cancel.setIconTextGap(0);
        PasswordRecovery_Button_Cancel.setMaximumSize(new java.awt.Dimension(90, 30));
        PasswordRecovery_Button_Cancel.setMinimumSize(new java.awt.Dimension(90, 30));
        PasswordRecovery_Button_Cancel.setPreferredSize(new java.awt.Dimension(90, 30));
        PasswordRecovery_Button_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordRecovery_Button_CancelActionPerformed(evt);
            }
        });
        PasswordRecovery_MainPanel.add(PasswordRecovery_Button_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 90, 30));

        PasswordRecovery_Button_Accept.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 18)); // NOI18N
        PasswordRecovery_Button_Accept.setText("Accept");
        PasswordRecovery_Button_Accept.setAlignmentY(0.0F);
        PasswordRecovery_Button_Accept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PasswordRecovery_Button_Accept.setFocusCycleRoot(true);
        PasswordRecovery_Button_Accept.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PasswordRecovery_Button_Accept.setIconTextGap(0);
        PasswordRecovery_Button_Accept.setMaximumSize(new java.awt.Dimension(90, 30));
        PasswordRecovery_Button_Accept.setMinimumSize(new java.awt.Dimension(90, 30));
        PasswordRecovery_Button_Accept.setPreferredSize(new java.awt.Dimension(90, 30));
        PasswordRecovery_Button_Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordRecovery_Button_AcceptActionPerformed(evt);
            }
        });
        PasswordRecovery_MainPanel.add(PasswordRecovery_Button_Accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 90, 30));

        javax.swing.GroupLayout PasswordRecoveryLayout = new javax.swing.GroupLayout(PasswordRecovery.getContentPane());
        PasswordRecovery.getContentPane().setLayout(PasswordRecoveryLayout);
        PasswordRecoveryLayout.setHorizontalGroup(
            PasswordRecoveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PasswordRecovery_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PasswordRecoveryLayout.setVerticalGroup(
            PasswordRecoveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PasswordRecovery_MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(closeProgram());
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);

        LayerPn.setMaximumSize(new java.awt.Dimension(1000, 600));
        LayerPn.setMinimumSize(new java.awt.Dimension(1000, 600));

        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 600));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 600);

        jPanel2.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 600));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel2);
        jPanel2.setBounds(0, 0, 1000, 600);

        jPanel3.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel3.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 600));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel3);
        jPanel3.setBounds(0, 0, 1000, 600);

        jPanel4.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel4.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanel4.setPreferredSize(new java.awt.Dimension(1000, 600));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel4);
        jPanel4.setBounds(0, 0, 1000, 600);

        jPanel5.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel5.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanel5.setPreferredSize(new java.awt.Dimension(1000, 600));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel5);
        jPanel5.setBounds(0, 0, 1000, 600);

        jPanel6.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel6.setMinimumSize(new java.awt.Dimension(1000, 600));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel6);
        jPanel6.setBounds(0, 0, 1000, 600);

        jPanel7.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel7.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanel7.setPreferredSize(new java.awt.Dimension(1000, 600));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel7);
        jPanel7.setBounds(0, 0, 1000, 600);

        jPanel8.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel8.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanel8.setPreferredSize(new java.awt.Dimension(1000, 600));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel8);
        jPanel8.setBounds(0, 0, 1000, 600);

        jPanel9.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel9.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanel9.setPreferredSize(new java.awt.Dimension(1000, 600));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel9);
        jPanel9.setBounds(0, 0, 1000, 600);

        jPanel10.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel10.setMinimumSize(new java.awt.Dimension(1000, 600));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel10);
        jPanel10.setBounds(0, 0, 1000, 600);

        jPanel11.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel11.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanel11.setPreferredSize(new java.awt.Dimension(1000, 600));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel11);
        jPanel11.setBounds(0, 0, 1000, 600);

        jPanel12.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel12.setMinimumSize(new java.awt.Dimension(1000, 600));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel12);
        jPanel12.setBounds(0, 0, 1000, 600);

        jPanel13.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel13.setMinimumSize(new java.awt.Dimension(1000, 600));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel13);
        jPanel13.setBounds(0, 0, 1000, 600);

        jPanel14.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel14.setMinimumSize(new java.awt.Dimension(1000, 600));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel14);
        jPanel14.setBounds(0, 0, 1000, 600);

        jPanel15.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel15.setMinimumSize(new java.awt.Dimension(1000, 600));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel15);
        jPanel15.setBounds(0, 0, 1000, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LayerPn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LayerPn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        LayerPn.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cofirmExit_button_AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cofirmExit_button_AcceptActionPerformed
       //controlador.guardarPrograma();
       System.exit(0);
    }//GEN-LAST:event_cofirmExit_button_AcceptActionPerformed

    private void cofirmExit_button_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cofirmExit_button_CancelActionPerformed
        confirmExit.setVisible(false);
        LayerPn.setVisible(true);
    }//GEN-LAST:event_cofirmExit_button_CancelActionPerformed

    private void LogIn_TextField_UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogIn_TextField_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogIn_TextField_UserNameActionPerformed

    private void LogIn_Button_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogIn_Button_SignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogIn_Button_SignUpActionPerformed

    private void LogIn_Button_AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogIn_Button_AcceptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogIn_Button_AcceptActionPerformed

    private void LogIn_Button_PasswordRecoveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogIn_Button_PasswordRecoveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogIn_Button_PasswordRecoveryActionPerformed

    private void SignUp_TextField_2ndSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_TextField_2ndSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_TextField_2ndSurnameActionPerformed

    private void SignUp_Button_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_Button_CancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_Button_CancelActionPerformed

    private void SignUp_Button_AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_Button_AcceptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_Button_AcceptActionPerformed

    private void SignUp_TextField_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_TextField_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_TextField_UsernameActionPerformed

    private void SignUp_TextField_MiddleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_TextField_MiddleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_TextField_MiddleNameActionPerformed

    private void SignUp_TextField_1stSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_TextField_1stSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_TextField_1stSurnameActionPerformed

    private void SignUp_TextField_FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_TextField_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_TextField_FirstNameActionPerformed

    private void PasswordRecovery_TextField_UserName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordRecovery_TextField_UserName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordRecovery_TextField_UserName1ActionPerformed

    private void PasswordRecovery_Button_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordRecovery_Button_CancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordRecovery_Button_CancelActionPerformed

    private void PasswordRecovery_Button_AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordRecovery_Button_AcceptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordRecovery_Button_AcceptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane LayerPn;
    private javax.swing.JFrame LogIn;
    private javax.swing.JButton LogIn_Button_Accept;
    private javax.swing.JButton LogIn_Button_PasswordRecovery;
    private javax.swing.JButton LogIn_Button_SignUp;
    private javax.swing.JPanel LogIn_Header;
    private javax.swing.JLabel LogIn_LabelPassword8;
    private javax.swing.JLabel LogIn_Label_Password;
    private javax.swing.JLabel LogIn_Label_PasswordRecovery;
    private javax.swing.JLabel LogIn_Label_UserName;
    private javax.swing.JLabel LogIn_Logo02;
    private javax.swing.JPanel LogIn_MainPanel;
    private javax.swing.JPasswordField LogIn_PasswordField_Password;
    private javax.swing.JTextField LogIn_TextField_UserName;
    private javax.swing.JLabel LogIn_logo01;
    private javax.swing.JFrame PasswordRecovery;
    private javax.swing.JButton PasswordRecovery_Button_Accept;
    private javax.swing.JButton PasswordRecovery_Button_Cancel;
    private javax.swing.JPanel PasswordRecovery_Header;
    private javax.swing.JLabel PasswordRecovery_Label_Tittle;
    private javax.swing.JLabel PasswordRecovery_Label_UserName;
    private javax.swing.JPanel PasswordRecovery_MainPanel;
    private javax.swing.JTextField PasswordRecovery_TextField_UserName1;
    private javax.swing.JLabel PasswordRecovery_logo2;
    private javax.swing.JFrame SignUp;
    private javax.swing.JButton SignUp_Button_Accept;
    private javax.swing.JButton SignUp_Button_Address;
    private javax.swing.JButton SignUp_Button_Cancel;
    private javax.swing.JButton SignUp_Button_ChooseAPhoto;
    private javax.swing.JFormattedTextField SignUp_FormattedTextField_BirthDate1;
    private javax.swing.JFormattedTextField SignUp_FormattedTextField_Email;
    private javax.swing.JFormattedTextField SignUp_FormattedTextField_Password;
    private javax.swing.JPanel SignUp_Header;
    private javax.swing.JLabel SignUp_Label_1stSurname;
    private javax.swing.JLabel SignUp_Label_2ndSurname;
    private javax.swing.JLabel SignUp_Label_BirthDate;
    private javax.swing.JLabel SignUp_Label_Direction;
    private javax.swing.JLabel SignUp_Label_Email;
    private javax.swing.JLabel SignUp_Label_FirstName;
    private javax.swing.JLabel SignUp_Label_MiddleName;
    private javax.swing.JLabel SignUp_Label_Password;
    private javax.swing.JLabel SignUp_Label_Tittle;
    private javax.swing.JLabel SignUp_Label_Username;
    private javax.swing.JLabel SignUp_Logo2;
    private javax.swing.JPanel SignUp_MainPanel;
    private javax.swing.JTextField SignUp_TextField_1stSurname;
    private javax.swing.JTextField SignUp_TextField_2ndSurname;
    private javax.swing.JTextField SignUp_TextField_FirstName;
    private javax.swing.JTextField SignUp_TextField_MiddleName;
    private javax.swing.JTextField SignUp_TextField_Username;
    private javax.swing.JButton cofirmExit_button_Accept;
    private javax.swing.JButton cofirmExit_button_Cancel;
    private javax.swing.JLabel cofirmExit_label_tittle;
    private javax.swing.JDialog confirmExit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
