/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import java.awt.Component;
import javax.imageio.ImageIO;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author David B
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();

        this.setLocationRelativeTo(null);
        this.setVisible(false);
        this.setEnabled(false);
        
        
        initializeInterface();
        
    }
    
    private  void initializeInterface(){

        LogIn.setVisible(true);
        LogIn.setLocationRelativeTo(null);
        
        confirmExit.setVisible(false);
        confirmExit.setLocationRelativeTo(null);
        
        LogIn.setVisible(true);
        LogIn.setLocationRelativeTo(null);
        
    }
   
    private void openFrameCloseFrame(JFrame openFrame, JFrame closeFrame){
        openFrame.setVisible(true);
        openFrame.setLocationRelativeTo(null);
        closeFrame.setVisible(false);
    }
    
    private void hideEveryPanelExceptThis(JPanel panel, boolean ... flagCleanPanel){
        boolean flagrResponseClean = (flagCleanPanel.length >= 1) ? flagCleanPanel[0] : false;
        
        for(Component component : LayerPn.getComponents()) 
            if(component instanceof JPanel)
                component.setVisible(false);
        
        if(flagrResponseClean) cleanWindow(panel);
        
        panel.setVisible(true);
    }
     
     private void cleanWindow(JPanel panel){
        for(Component component : panel.getComponents()){   
            if(component instanceof JTextField){
                JTextField comp = (JTextField) component;
                comp.setText("");
            }
            else if (component instanceof JComboBox){
                JComboBox comp = (JComboBox) component;
                comp.setSelectedIndex(0);
            }
            else if(component instanceof JFormattedTextField){
                JFormattedTextField comp = (JFormattedTextField) component;
                comp.setText("");
            }
            else if(component instanceof JTextField){
                JTextField comp = (JTextField) component;
                comp.setText("");
            }
            else if(component instanceof JTextArea){
                JTextArea comp = (JTextArea) component;
                comp.setText("");
            }
            else if(component instanceof JTable){
                JTable comp = (JTable) component;
                comp.removeAll();
            }
        }
    }
     
    private int closeProgram(){
        confirmExit.setVisible(true);
        confirmExit.toFront();
        confirmExit.requestFocus();
        return 0;
    }

        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmExit = new javax.swing.JDialog();
        cofirmExit_label_tittle = new javax.swing.JLabel();
        cofirmExit_button_Accept = new javax.swing.JButton();
        cofirmExit_button_Cancel = new javax.swing.JButton();
        LogIn = new javax.swing.JFrame();
        LogIn_MainPanel = new javax.swing.JPanel();
        LogIn_Header = new javax.swing.JPanel();
        LogIn_logo01 = new javax.swing.JLabel();
        LogIn_Logo02 = new javax.swing.JLabel();
        LogIn_TextField_UserName = new javax.swing.JTextField();
        LogIn_Label_UserName = new javax.swing.JLabel();
        LogIn_Label_Password = new javax.swing.JLabel();
        LogIn_PasswordField_Password = new javax.swing.JPasswordField();
        LogIn_Button_SignUp = new javax.swing.JButton();
        LogIn_Button_Accept = new javax.swing.JButton();
        LogIn_Button_PasswordRecovery = new javax.swing.JButton();
        LogIn_Label_PasswordRecovery = new javax.swing.JLabel();
        LogIn_Button_Accept1 = new javax.swing.JButton();
        SignUp = new javax.swing.JFrame();
        SignUp_MainPanel = new javax.swing.JPanel();
        SignUp_Header = new javax.swing.JPanel();
        SignUp_Logo2 = new javax.swing.JLabel();
        SignUp_Label_Tittle = new javax.swing.JLabel();
        SignUp_TextField_2ndSurname = new javax.swing.JTextField();
        SignUp_Label_Username = new javax.swing.JLabel();
        SignUp_Button_Cancel = new javax.swing.JButton();
        SignUp_Button_Accept = new javax.swing.JButton();
        SignUp_TextField_Username = new javax.swing.JTextField();
        SignUp_Label_MiddleName = new javax.swing.JLabel();
        SignUp_TextField_MiddleName = new javax.swing.JTextField();
        SignUp_Label_1stSurname = new javax.swing.JLabel();
        SignUp_TextField_1stSurname = new javax.swing.JTextField();
        SignUp_Label_Direction = new javax.swing.JLabel();
        SignUp_Label_2ndSurname = new javax.swing.JLabel();
        SignUp_FormattedTextField_Password = new javax.swing.JFormattedTextField();
        SignUp_Label_BirthDate = new javax.swing.JLabel();
        SignUp_Button_Address = new javax.swing.JButton();
        SignUp_Label_Password = new javax.swing.JLabel();
        SignUp_Button_ChooseAPhoto = new javax.swing.JButton();
        LogIn_LabelPassword8 = new javax.swing.JLabel();
        SignUp_Label_FirstName = new javax.swing.JLabel();
        SignUp_TextField_FirstName = new javax.swing.JTextField();
        SignUp_Label_Email = new javax.swing.JLabel();
        SignUp_FormattedTextField_Email = new javax.swing.JFormattedTextField();
        SignUp_FormattedTextField_BirthDate1 = new javax.swing.JFormattedTextField();
        PasswordRecovery = new javax.swing.JFrame();
        PasswordRecovery_MainPanel = new javax.swing.JPanel();
        PasswordRecovery_Header = new javax.swing.JPanel();
        PasswordRecovery_logo2 = new javax.swing.JLabel();
        PasswordRecovery_Label_Tittle = new javax.swing.JLabel();
        PasswordRecovery_TextField_UserName1 = new javax.swing.JTextField();
        PasswordRecovery_Label_UserName = new javax.swing.JLabel();
        PasswordRecovery_Button_Cancel = new javax.swing.JButton();
        PasswordRecovery_Button_Accept = new javax.swing.JButton();
        photoChooser = new javax.swing.JFileChooser();
        mainWindow = new javax.swing.JFrame();
        LayerPn = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        Address = new javax.swing.JFrame();
        Address_MainPanel = new javax.swing.JPanel();
        Address_Header = new javax.swing.JPanel();
        Address_Logo3 = new javax.swing.JLabel();
        Address_Label_Tittle = new javax.swing.JLabel();
        Address_Label_DetailedDescription = new javax.swing.JLabel();
        Address_Label_Country = new javax.swing.JLabel();
        Address_Label_Province = new javax.swing.JLabel();
        Address_ComboBox_Country = new javax.swing.JComboBox<>();
        Address_ComboBox_District = new javax.swing.JComboBox<>();
        Address_ComboBox_Canton = new javax.swing.JComboBox<>();
        Address_ComboBox_Province = new javax.swing.JComboBox<>();
        Address_Label_District = new javax.swing.JLabel();
        Address_ScrollPane_DetailedDescriptionContainer = new javax.swing.JScrollPane();
        Address_TextArea_DetailedDescription = new javax.swing.JTextArea();
        Address_Label_Canton = new javax.swing.JLabel();
        Address_Button_Accept = new javax.swing.JButton();

        confirmExit.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        confirmExit.setMaximumSize(new java.awt.Dimension(400, 207));
        confirmExit.setMinimumSize(new java.awt.Dimension(400, 207));

        cofirmExit_label_tittle.setFont(new java.awt.Font("Kozuka Mincho Pro L", 0, 24)); // NOI18N
        cofirmExit_label_tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cofirmExit_label_tittle.setText("Do you want to close the program?");

        cofirmExit_button_Accept.setText("Accept");
        cofirmExit_button_Accept.setMaximumSize(new java.awt.Dimension(90, 30));
        cofirmExit_button_Accept.setMinimumSize(new java.awt.Dimension(90, 30));
        cofirmExit_button_Accept.setPreferredSize(new java.awt.Dimension(90, 30));
        cofirmExit_button_Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cofirmExit_button_AcceptActionPerformed(evt);
            }
        });

        cofirmExit_button_Cancel.setText("Cancel");
        cofirmExit_button_Cancel.setMaximumSize(new java.awt.Dimension(90, 30));
        cofirmExit_button_Cancel.setMinimumSize(new java.awt.Dimension(90, 30));
        cofirmExit_button_Cancel.setPreferredSize(new java.awt.Dimension(90, 30));
        cofirmExit_button_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cofirmExit_button_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout confirmExitLayout = new javax.swing.GroupLayout(confirmExit.getContentPane());
        confirmExit.getContentPane().setLayout(confirmExitLayout);
        confirmExitLayout.setHorizontalGroup(
            confirmExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, confirmExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cofirmExit_label_tittle, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(confirmExitLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(cofirmExit_button_Accept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(cofirmExit_button_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        confirmExitLayout.setVerticalGroup(
            confirmExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmExitLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cofirmExit_label_tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(confirmExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cofirmExit_button_Accept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cofirmExit_button_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        LogIn.setDefaultCloseOperation(closeProgram());
        LogIn.setTitle("Log In");
        LogIn.setAutoRequestFocus(false);
        LogIn.setBackground(new java.awt.Color(255, 180, 162));
        LogIn.setMaximumSize(new java.awt.Dimension(600, 420));
        LogIn.setMinimumSize(new java.awt.Dimension(600, 420));
        LogIn.setUndecorated(true);
        LogIn.setPreferredSize(new java.awt.Dimension(600, 420));

        LogIn_MainPanel.setBackground(new java.awt.Color(109, 104, 117));
        LogIn_MainPanel.setToolTipText("");
        LogIn_MainPanel.setMaximumSize(new java.awt.Dimension(600, 420));
        LogIn_MainPanel.setMinimumSize(new java.awt.Dimension(600, 420));
        LogIn_MainPanel.setName(""); // NOI18N
        LogIn_MainPanel.setPreferredSize(new java.awt.Dimension(600, 420));
        LogIn_MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogIn_Header.setBackground(new java.awt.Color(255, 180, 162));
        LogIn_Header.setMaximumSize(new java.awt.Dimension(600, 150));
        LogIn_Header.setMinimumSize(new java.awt.Dimension(600, 150));
        LogIn_Header.setPreferredSize(new java.awt.Dimension(600, 150));

        LogIn_logo01.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\2 SEMESTRE 20\\Bases de Datos\\Proyecto 01\\Protyecto-1\\Proyecto1BD\\src\\main\\java\\UserInterface\\images\\LogoBD_1.png")); // NOI18N

        LogIn_Logo02.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\2 SEMESTRE 20\\Bases de Datos\\Proyecto 01\\Protyecto-1\\Proyecto1BD\\src\\main\\java\\UserInterface\\images\\LogoBD_2.png")); // NOI18N

        javax.swing.GroupLayout LogIn_HeaderLayout = new javax.swing.GroupLayout(LogIn_Header);
        LogIn_Header.setLayout(LogIn_HeaderLayout);
        LogIn_HeaderLayout.setHorizontalGroup(
            LogIn_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogIn_HeaderLayout.createSequentialGroup()
                .addComponent(LogIn_logo01, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LogIn_Logo02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );
        LogIn_HeaderLayout.setVerticalGroup(
            LogIn_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogIn_logo01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogIn_Logo02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        LogIn_MainPanel.add(LogIn_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        LogIn_TextField_UserName.setMaximumSize(new java.awt.Dimension(90, 30));
        LogIn_TextField_UserName.setMinimumSize(new java.awt.Dimension(90, 30));
        LogIn_TextField_UserName.setPreferredSize(new java.awt.Dimension(90, 30));
        LogIn_TextField_UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogIn_TextField_UserNameActionPerformed(evt);
            }
        });
        LogIn_MainPanel.add(LogIn_TextField_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 218, 260, -1));

        LogIn_Label_UserName.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 24)); // NOI18N
        LogIn_Label_UserName.setForeground(new java.awt.Color(255, 255, 255));
        LogIn_Label_UserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogIn_Label_UserName.setText("Username:");
        LogIn_Label_UserName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        LogIn_MainPanel.add(LogIn_Label_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 215, 148, 30));

        LogIn_Label_Password.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 24)); // NOI18N
        LogIn_Label_Password.setForeground(new java.awt.Color(255, 255, 255));
        LogIn_Label_Password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogIn_Label_Password.setText("Password:");
        LogIn_Label_Password.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        LogIn_MainPanel.add(LogIn_Label_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 266, 148, 30));

        LogIn_PasswordField_Password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        LogIn_MainPanel.add(LogIn_PasswordField_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 266, 260, 30));

        LogIn_Button_SignUp.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 18)); // NOI18N
        LogIn_Button_SignUp.setText("Sign up ");
        LogIn_Button_SignUp.setAlignmentY(0.0F);
        LogIn_Button_SignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogIn_Button_SignUp.setFocusCycleRoot(true);
        LogIn_Button_SignUp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LogIn_Button_SignUp.setIconTextGap(0);
        LogIn_Button_SignUp.setMaximumSize(new java.awt.Dimension(90, 30));
        LogIn_Button_SignUp.setMinimumSize(new java.awt.Dimension(90, 30));
        LogIn_Button_SignUp.setPreferredSize(new java.awt.Dimension(90, 30));
        LogIn_Button_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogIn_Button_SignUpActionPerformed(evt);
            }
        });
        LogIn_MainPanel.add(LogIn_Button_SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 110, 40));

        LogIn_Button_Accept.setBackground(new java.awt.Color(255, 255, 255));
        LogIn_Button_Accept.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 18)); // NOI18N
        LogIn_Button_Accept.setForeground(new java.awt.Color(204, 0, 0));
        LogIn_Button_Accept.setText("Exit");
        LogIn_Button_Accept.setAlignmentY(0.0F);
        LogIn_Button_Accept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogIn_Button_Accept.setFocusCycleRoot(true);
        LogIn_Button_Accept.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LogIn_Button_Accept.setIconTextGap(0);
        LogIn_Button_Accept.setMaximumSize(new java.awt.Dimension(90, 30));
        LogIn_Button_Accept.setMinimumSize(new java.awt.Dimension(90, 30));
        LogIn_Button_Accept.setPreferredSize(new java.awt.Dimension(90, 30));
        LogIn_Button_Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogIn_Button_AcceptActionPerformed(evt);
            }
        });
        LogIn_MainPanel.add(LogIn_Button_Accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 70, 30));

        LogIn_Button_PasswordRecovery.setBorderPainted(false);
        LogIn_Button_PasswordRecovery.setContentAreaFilled(false);
        LogIn_Button_PasswordRecovery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogIn_Button_PasswordRecovery.setFocusPainted(false);
        LogIn_Button_PasswordRecovery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogIn_Button_PasswordRecoveryActionPerformed(evt);
            }
        });
        LogIn_MainPanel.add(LogIn_Button_PasswordRecovery, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 160, 20));

        LogIn_Label_PasswordRecovery.setFont(new java.awt.Font("Kozuka Mincho Pro L", 2, 14)); // NOI18N
        LogIn_Label_PasswordRecovery.setForeground(new java.awt.Color(204, 204, 204));
        LogIn_Label_PasswordRecovery.setText("Password Recovery");
        LogIn_Label_PasswordRecovery.setToolTipText("");
        LogIn_Label_PasswordRecovery.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        LogIn_Label_PasswordRecovery.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LogIn_MainPanel.add(LogIn_Label_PasswordRecovery, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 170, 20));

        LogIn_Button_Accept1.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 18)); // NOI18N
        LogIn_Button_Accept1.setText("Accept");
        LogIn_Button_Accept1.setAlignmentY(0.0F);
        LogIn_Button_Accept1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogIn_Button_Accept1.setFocusCycleRoot(true);
        LogIn_Button_Accept1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LogIn_Button_Accept1.setIconTextGap(0);
        LogIn_Button_Accept1.setMaximumSize(new java.awt.Dimension(90, 30));
        LogIn_Button_Accept1.setMinimumSize(new java.awt.Dimension(90, 30));
        LogIn_Button_Accept1.setPreferredSize(new java.awt.Dimension(90, 30));
        LogIn_Button_Accept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogIn_Button_Accept1ActionPerformed(evt);
            }
        });
        LogIn_MainPanel.add(LogIn_Button_Accept1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 110, 40));

        javax.swing.GroupLayout LogInLayout = new javax.swing.GroupLayout(LogIn.getContentPane());
        LogIn.getContentPane().setLayout(LogInLayout);
        LogInLayout.setHorizontalGroup(
            LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogIn_MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        LogInLayout.setVerticalGroup(
            LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogIn_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        SignUp.setAlwaysOnTop(true);
        SignUp.setAutoRequestFocus(false);
        SignUp.setBackground(new java.awt.Color(255, 180, 162));
        SignUp.setMaximumSize(new java.awt.Dimension(676, 420));
        SignUp.setMinimumSize(new java.awt.Dimension(676, 420));
        SignUp.setUndecorated(true);

        SignUp_MainPanel.setBackground(new java.awt.Color(109, 104, 117));
        SignUp_MainPanel.setToolTipText("");
        SignUp_MainPanel.setMaximumSize(new java.awt.Dimension(676, 420));
        SignUp_MainPanel.setMinimumSize(new java.awt.Dimension(676, 420));
        SignUp_MainPanel.setName(""); // NOI18N
        SignUp_MainPanel.setPreferredSize(new java.awt.Dimension(676, 420));
        SignUp_MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignUp_Header.setBackground(new java.awt.Color(255, 180, 162));
        SignUp_Header.setMaximumSize(new java.awt.Dimension(600, 150));
        SignUp_Header.setMinimumSize(new java.awt.Dimension(600, 150));

        SignUp_Logo2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\2 SEMESTRE 20\\Bases de Datos\\Proyecto 01\\Protyecto-1\\Proyecto1BD\\src\\main\\java\\UserInterface\\images\\LogoBD_2_50p.png")); // NOI18N

        SignUp_Label_Tittle.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 2, 48)); // NOI18N
        SignUp_Label_Tittle.setForeground(new java.awt.Color(90, 87, 96));
        SignUp_Label_Tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUp_Label_Tittle.setText("Sign Up");
        SignUp_Label_Tittle.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout SignUp_HeaderLayout = new javax.swing.GroupLayout(SignUp_Header);
        SignUp_Header.setLayout(SignUp_HeaderLayout);
        SignUp_HeaderLayout.setHorizontalGroup(
            SignUp_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUp_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SignUp_Logo2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SignUp_Label_Tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        SignUp_HeaderLayout.setVerticalGroup(
            SignUp_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUp_HeaderLayout.createSequentialGroup()
                .addGroup(SignUp_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SignUp_Logo2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(SignUp_Label_Tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 90, Short.MAX_VALUE))
        );

        SignUp_MainPanel.add(SignUp_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 60));

        SignUp_TextField_2ndSurname.setMaximumSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_2ndSurname.setMinimumSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_2ndSurname.setPreferredSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_2ndSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_TextField_2ndSurnameActionPerformed(evt);
            }
        });
        SignUp_MainPanel.add(SignUp_TextField_2ndSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 170, -1));

        SignUp_Label_Username.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 18)); // NOI18N
        SignUp_Label_Username.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_Label_Username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SignUp_Label_Username.setText("Username");
        SignUp_Label_Username.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SignUp_MainPanel.add(SignUp_Label_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 120, 20));

        SignUp_Button_Cancel.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 18)); // NOI18N
        SignUp_Button_Cancel.setText("Cancel");
        SignUp_Button_Cancel.setAlignmentY(0.0F);
        SignUp_Button_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUp_Button_Cancel.setFocusCycleRoot(true);
        SignUp_Button_Cancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SignUp_Button_Cancel.setIconTextGap(0);
        SignUp_Button_Cancel.setMaximumSize(new java.awt.Dimension(90, 30));
        SignUp_Button_Cancel.setMinimumSize(new java.awt.Dimension(90, 30));
        SignUp_Button_Cancel.setPreferredSize(new java.awt.Dimension(90, 30));
        SignUp_Button_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_Button_CancelActionPerformed(evt);
            }
        });
        SignUp_MainPanel.add(SignUp_Button_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 120, 40));

        SignUp_Button_Accept.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 18)); // NOI18N
        SignUp_Button_Accept.setText("Accept");
        SignUp_Button_Accept.setAlignmentY(0.0F);
        SignUp_Button_Accept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUp_Button_Accept.setFocusCycleRoot(true);
        SignUp_Button_Accept.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SignUp_Button_Accept.setIconTextGap(0);
        SignUp_Button_Accept.setMaximumSize(new java.awt.Dimension(90, 30));
        SignUp_Button_Accept.setMinimumSize(new java.awt.Dimension(90, 30));
        SignUp_Button_Accept.setPreferredSize(new java.awt.Dimension(90, 30));
        SignUp_Button_Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_Button_AcceptActionPerformed(evt);
            }
        });
        SignUp_MainPanel.add(SignUp_Button_Accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 110, 40));

        SignUp_TextField_Username.setMaximumSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_Username.setMinimumSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_Username.setPreferredSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_TextField_UsernameActionPerformed(evt);
            }
        });
        SignUp_MainPanel.add(SignUp_TextField_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 170, 30));

        SignUp_Label_MiddleName.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 18)); // NOI18N
        SignUp_Label_MiddleName.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_Label_MiddleName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SignUp_Label_MiddleName.setText("Middle name:");
        SignUp_Label_MiddleName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SignUp_MainPanel.add(SignUp_Label_MiddleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 120, 20));

        SignUp_TextField_MiddleName.setMaximumSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_MiddleName.setMinimumSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_MiddleName.setPreferredSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_MiddleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_TextField_MiddleNameActionPerformed(evt);
            }
        });
        SignUp_MainPanel.add(SignUp_TextField_MiddleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 170, -1));

        SignUp_Label_1stSurname.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 18)); // NOI18N
        SignUp_Label_1stSurname.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_Label_1stSurname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SignUp_Label_1stSurname.setText("1st Surname:");
        SignUp_Label_1stSurname.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SignUp_MainPanel.add(SignUp_Label_1stSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 120, 20));

        SignUp_TextField_1stSurname.setMaximumSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_1stSurname.setMinimumSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_1stSurname.setPreferredSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_1stSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_TextField_1stSurnameActionPerformed(evt);
            }
        });
        SignUp_MainPanel.add(SignUp_TextField_1stSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 170, 30));

        SignUp_Label_Direction.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 18)); // NOI18N
        SignUp_Label_Direction.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_Label_Direction.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SignUp_Label_Direction.setText("Address:");
        SignUp_Label_Direction.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SignUp_MainPanel.add(SignUp_Label_Direction, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 120, 20));

        SignUp_Label_2ndSurname.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 18)); // NOI18N
        SignUp_Label_2ndSurname.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_Label_2ndSurname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SignUp_Label_2ndSurname.setText("2nd Surname:");
        SignUp_Label_2ndSurname.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SignUp_MainPanel.add(SignUp_Label_2ndSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 120, 20));
        SignUp_MainPanel.add(SignUp_FormattedTextField_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 170, 30));

        SignUp_Label_BirthDate.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 18)); // NOI18N
        SignUp_Label_BirthDate.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_Label_BirthDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SignUp_Label_BirthDate.setText("Birth date:");
        SignUp_Label_BirthDate.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SignUp_MainPanel.add(SignUp_Label_BirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 120, 20));

        SignUp_Button_Address.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        SignUp_Button_Address.setText("Your address");
        SignUp_Button_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_Button_AddressActionPerformed(evt);
            }
        });
        SignUp_MainPanel.add(SignUp_Button_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 170, 30));

        SignUp_Label_Password.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 18)); // NOI18N
        SignUp_Label_Password.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_Label_Password.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SignUp_Label_Password.setText("Password");
        SignUp_Label_Password.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SignUp_MainPanel.add(SignUp_Label_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 120, 20));

        SignUp_Button_ChooseAPhoto.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        SignUp_Button_ChooseAPhoto.setText("Choose a photo");
        SignUp_Button_ChooseAPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_Button_ChooseAPhotoActionPerformed(evt);
            }
        });
        SignUp_MainPanel.add(SignUp_Button_ChooseAPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 170, 30));

        LogIn_LabelPassword8.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 18)); // NOI18N
        LogIn_LabelPassword8.setForeground(new java.awt.Color(255, 255, 255));
        LogIn_LabelPassword8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LogIn_LabelPassword8.setText("Photo:");
        LogIn_LabelPassword8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SignUp_MainPanel.add(LogIn_LabelPassword8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 120, 20));

        SignUp_Label_FirstName.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 18)); // NOI18N
        SignUp_Label_FirstName.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_Label_FirstName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SignUp_Label_FirstName.setText("First name:");
        SignUp_Label_FirstName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SignUp_MainPanel.add(SignUp_Label_FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 20));

        SignUp_TextField_FirstName.setMaximumSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_FirstName.setMinimumSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_FirstName.setPreferredSize(new java.awt.Dimension(90, 30));
        SignUp_TextField_FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_TextField_FirstNameActionPerformed(evt);
            }
        });
        SignUp_MainPanel.add(SignUp_TextField_FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 170, 30));

        SignUp_Label_Email.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 18)); // NOI18N
        SignUp_Label_Email.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_Label_Email.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SignUp_Label_Email.setText("Email:");
        SignUp_Label_Email.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SignUp_MainPanel.add(SignUp_Label_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 120, 20));
        SignUp_MainPanel.add(SignUp_FormattedTextField_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 170, 30));

        SignUp_FormattedTextField_BirthDate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_FormattedTextField_BirthDate1ActionPerformed(evt);
            }
        });
        SignUp_MainPanel.add(SignUp_FormattedTextField_BirthDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 170, 30));

        javax.swing.GroupLayout SignUpLayout = new javax.swing.GroupLayout(SignUp.getContentPane());
        SignUp.getContentPane().setLayout(SignUpLayout);
        SignUpLayout.setHorizontalGroup(
            SignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignUp_MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SignUpLayout.setVerticalGroup(
            SignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignUp_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PasswordRecovery.setAlwaysOnTop(true);
        PasswordRecovery.setAutoRequestFocus(false);
        PasswordRecovery.setBackground(new java.awt.Color(255, 180, 162));
        PasswordRecovery.setMinimumSize(new java.awt.Dimension(500, 300));
        PasswordRecovery.setUndecorated(true);

        PasswordRecovery_MainPanel.setBackground(new java.awt.Color(109, 104, 117));
        PasswordRecovery_MainPanel.setToolTipText("");
        PasswordRecovery_MainPanel.setMaximumSize(new java.awt.Dimension(500, 300));
        PasswordRecovery_MainPanel.setMinimumSize(new java.awt.Dimension(500, 300));
        PasswordRecovery_MainPanel.setName(""); // NOI18N
        PasswordRecovery_MainPanel.setPreferredSize(new java.awt.Dimension(500, 300));
        PasswordRecovery_MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PasswordRecovery_Header.setBackground(new java.awt.Color(255, 180, 162));
        PasswordRecovery_Header.setMaximumSize(new java.awt.Dimension(600, 150));
        PasswordRecovery_Header.setMinimumSize(new java.awt.Dimension(600, 150));

        PasswordRecovery_logo2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\2 SEMESTRE 20\\Bases de Datos\\Proyecto 01\\Protyecto-1\\Proyecto1BD\\src\\main\\java\\UserInterface\\images\\LogoBD_1_75p.png")); // NOI18N

        PasswordRecovery_Label_Tittle.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 2, 44)); // NOI18N
        PasswordRecovery_Label_Tittle.setForeground(new java.awt.Color(90, 87, 96));
        PasswordRecovery_Label_Tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordRecovery_Label_Tittle.setText("Password Recovery");
        PasswordRecovery_Label_Tittle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PasswordRecovery_Label_Tittle.setFocusable(false);

        javax.swing.GroupLayout PasswordRecovery_HeaderLayout = new javax.swing.GroupLayout(PasswordRecovery_Header);
        PasswordRecovery_Header.setLayout(PasswordRecovery_HeaderLayout);
        PasswordRecovery_HeaderLayout.setHorizontalGroup(
            PasswordRecovery_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasswordRecovery_HeaderLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(PasswordRecovery_logo2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PasswordRecovery_Label_Tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        PasswordRecovery_HeaderLayout.setVerticalGroup(
            PasswordRecovery_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasswordRecovery_HeaderLayout.createSequentialGroup()
                .addGroup(PasswordRecovery_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PasswordRecovery_Label_Tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordRecovery_logo2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 78, Short.MAX_VALUE))
        );

        PasswordRecovery_MainPanel.add(PasswordRecovery_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 80));

        PasswordRecovery_TextField_UserName1.setMaximumSize(new java.awt.Dimension(90, 30));
        PasswordRecovery_TextField_UserName1.setMinimumSize(new java.awt.Dimension(90, 30));
        PasswordRecovery_TextField_UserName1.setPreferredSize(new java.awt.Dimension(90, 30));
        PasswordRecovery_TextField_UserName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordRecovery_TextField_UserName1ActionPerformed(evt);
            }
        });
        PasswordRecovery_MainPanel.add(PasswordRecovery_TextField_UserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 260, -1));

        PasswordRecovery_Label_UserName.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 24)); // NOI18N
        PasswordRecovery_Label_UserName.setForeground(new java.awt.Color(255, 255, 255));
        PasswordRecovery_Label_UserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordRecovery_Label_UserName.setText("Username:");
        PasswordRecovery_Label_UserName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PasswordRecovery_Label_UserName.setFocusable(false);
        PasswordRecovery_MainPanel.add(PasswordRecovery_Label_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 148, 30));

        PasswordRecovery_Button_Cancel.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 18)); // NOI18N
        PasswordRecovery_Button_Cancel.setText("Cancel");
        PasswordRecovery_Button_Cancel.setAlignmentY(0.0F);
        PasswordRecovery_Button_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PasswordRecovery_Button_Cancel.setFocusCycleRoot(true);
        PasswordRecovery_Button_Cancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PasswordRecovery_Button_Cancel.setIconTextGap(0);
        PasswordRecovery_Button_Cancel.setMaximumSize(new java.awt.Dimension(90, 30));
        PasswordRecovery_Button_Cancel.setMinimumSize(new java.awt.Dimension(90, 30));
        PasswordRecovery_Button_Cancel.setPreferredSize(new java.awt.Dimension(90, 30));
        PasswordRecovery_Button_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordRecovery_Button_CancelActionPerformed(evt);
            }
        });
        PasswordRecovery_MainPanel.add(PasswordRecovery_Button_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 90, 30));

        PasswordRecovery_Button_Accept.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 18)); // NOI18N
        PasswordRecovery_Button_Accept.setText("Accept");
        PasswordRecovery_Button_Accept.setAlignmentY(0.0F);
        PasswordRecovery_Button_Accept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PasswordRecovery_Button_Accept.setFocusCycleRoot(true);
        PasswordRecovery_Button_Accept.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PasswordRecovery_Button_Accept.setIconTextGap(0);
        PasswordRecovery_Button_Accept.setMaximumSize(new java.awt.Dimension(90, 30));
        PasswordRecovery_Button_Accept.setMinimumSize(new java.awt.Dimension(90, 30));
        PasswordRecovery_Button_Accept.setPreferredSize(new java.awt.Dimension(90, 30));
        PasswordRecovery_Button_Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordRecovery_Button_AcceptActionPerformed(evt);
            }
        });
        PasswordRecovery_MainPanel.add(PasswordRecovery_Button_Accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 90, 30));

        javax.swing.GroupLayout PasswordRecoveryLayout = new javax.swing.GroupLayout(PasswordRecovery.getContentPane());
        PasswordRecovery.getContentPane().setLayout(PasswordRecoveryLayout);
        PasswordRecoveryLayout.setHorizontalGroup(
            PasswordRecoveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PasswordRecovery_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PasswordRecoveryLayout.setVerticalGroup(
            PasswordRecoveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PasswordRecovery_MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        photoChooser.setDialogTitle("");
        photoChooser.setFileFilter(new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes()));

        mainWindow.setDefaultCloseOperation(closeProgram());
        mainWindow.setMaximumSize(new java.awt.Dimension(860, 540));
        mainWindow.setMinimumSize(new java.awt.Dimension(860, 540));
        mainWindow.setPreferredSize(new java.awt.Dimension(860, 540));

        LayerPn.setMaximumSize(new java.awt.Dimension(860, 540));
        LayerPn.setMinimumSize(new java.awt.Dimension(860, 540));
        LayerPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(860, 540));
        jPanel1.setMinimumSize(new java.awt.Dimension(860, 540));
        jPanel1.setPreferredSize(new java.awt.Dimension(860, 540));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel16.setMaximumSize(new java.awt.Dimension(860, 540));
        jPanel16.setMinimumSize(new java.awt.Dimension(860, 540));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel17.setMaximumSize(new java.awt.Dimension(860, 540));
        jPanel17.setMinimumSize(new java.awt.Dimension(860, 540));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel18.setMaximumSize(new java.awt.Dimension(860, 540));
        jPanel18.setMinimumSize(new java.awt.Dimension(860, 540));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel19.setMaximumSize(new java.awt.Dimension(860, 540));
        jPanel19.setMinimumSize(new java.awt.Dimension(860, 540));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel20.setMaximumSize(new java.awt.Dimension(860, 540));
        jPanel20.setMinimumSize(new java.awt.Dimension(860, 540));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel21.setMaximumSize(new java.awt.Dimension(860, 540));
        jPanel21.setMinimumSize(new java.awt.Dimension(860, 540));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel22.setMaximumSize(new java.awt.Dimension(860, 540));
        jPanel22.setMinimumSize(new java.awt.Dimension(860, 540));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        LayerPn.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout mainWindowLayout = new javax.swing.GroupLayout(mainWindow.getContentPane());
        mainWindow.getContentPane().setLayout(mainWindowLayout);
        mainWindowLayout.setHorizontalGroup(
            mainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainWindowLayout.createSequentialGroup()
                .addComponent(LayerPn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        mainWindowLayout.setVerticalGroup(
            mainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainWindowLayout.createSequentialGroup()
                .addComponent(LayerPn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        LayerPn.getAccessibleContext().setAccessibleName("");

        Address.setDefaultCloseOperation(closeProgram());
        Address.setTitle("Log In");
        Address.setAutoRequestFocus(false);
        Address.setBackground(new java.awt.Color(255, 180, 162));
        Address.setMaximumSize(new java.awt.Dimension(608, 420));
        Address.setMinimumSize(new java.awt.Dimension(608, 420));
        Address.setUndecorated(true);
        Address.setPreferredSize(new java.awt.Dimension(608, 420));

        Address_MainPanel.setBackground(new java.awt.Color(109, 104, 117));
        Address_MainPanel.setToolTipText("");
        Address_MainPanel.setMaximumSize(new java.awt.Dimension(608, 420));
        Address_MainPanel.setMinimumSize(new java.awt.Dimension(608, 420));
        Address_MainPanel.setName(""); // NOI18N
        Address_MainPanel.setPreferredSize(new java.awt.Dimension(608, 420));
        Address_MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Address_Header.setBackground(new java.awt.Color(255, 180, 162));
        Address_Header.setMaximumSize(new java.awt.Dimension(600, 150));
        Address_Header.setMinimumSize(new java.awt.Dimension(600, 150));

        Address_Logo3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\2 SEMESTRE 20\\Bases de Datos\\Proyecto 01\\Protyecto-1\\Proyecto1BD\\src\\main\\java\\UserInterface\\images\\LogoBD_2_50p.png")); // NOI18N

        Address_Label_Tittle.setBackground(new java.awt.Color(109, 104, 117));
        Address_Label_Tittle.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 48)); // NOI18N
        Address_Label_Tittle.setForeground(new java.awt.Color(109, 104, 117));
        Address_Label_Tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Address_Label_Tittle.setText("Address");
        Address_Label_Tittle.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout Address_HeaderLayout = new javax.swing.GroupLayout(Address_Header);
        Address_Header.setLayout(Address_HeaderLayout);
        Address_HeaderLayout.setHorizontalGroup(
            Address_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Address_HeaderLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Address_Logo3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(Address_Label_Tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        Address_HeaderLayout.setVerticalGroup(
            Address_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Address_Logo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Address_Label_Tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        Address_MainPanel.add(Address_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        Address_Label_DetailedDescription.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 24)); // NOI18N
        Address_Label_DetailedDescription.setForeground(new java.awt.Color(255, 255, 255));
        Address_Label_DetailedDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Address_Label_DetailedDescription.setText("Detailed description:");
        Address_Label_DetailedDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Address_MainPanel.add(Address_Label_DetailedDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 220, 30));

        Address_Label_Country.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 24)); // NOI18N
        Address_Label_Country.setForeground(new java.awt.Color(255, 255, 255));
        Address_Label_Country.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Address_Label_Country.setText("Country");
        Address_Label_Country.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Address_MainPanel.add(Address_Label_Country, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, 30));

        Address_Label_Province.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 24)); // NOI18N
        Address_Label_Province.setForeground(new java.awt.Color(255, 255, 255));
        Address_Label_Province.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Address_Label_Province.setText("Province");
        Address_Label_Province.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Address_MainPanel.add(Address_Label_Province, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 120, 30));

        Address_ComboBox_Country.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Address_MainPanel.add(Address_ComboBox_Country, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, 40));

        Address_ComboBox_District.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Address_MainPanel.add(Address_ComboBox_District, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 120, 40));

        Address_ComboBox_Canton.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Address_MainPanel.add(Address_ComboBox_Canton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 120, 40));

        Address_ComboBox_Province.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Address_MainPanel.add(Address_ComboBox_Province, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 120, 40));

        Address_Label_District.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 24)); // NOI18N
        Address_Label_District.setForeground(new java.awt.Color(255, 255, 255));
        Address_Label_District.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Address_Label_District.setText("District");
        Address_Label_District.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Address_MainPanel.add(Address_Label_District, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 120, 30));

        Address_TextArea_DetailedDescription.setColumns(20);
        Address_TextArea_DetailedDescription.setRows(5);
        Address_ScrollPane_DetailedDescriptionContainer.setViewportView(Address_TextArea_DetailedDescription);

        Address_MainPanel.add(Address_ScrollPane_DetailedDescriptionContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 340, 140));

        Address_Label_Canton.setFont(new java.awt.Font("Kozuka Mincho Pr6N L", 0, 24)); // NOI18N
        Address_Label_Canton.setForeground(new java.awt.Color(255, 255, 255));
        Address_Label_Canton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Address_Label_Canton.setText("Canton");
        Address_Label_Canton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Address_MainPanel.add(Address_Label_Canton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 120, 30));

        Address_Button_Accept.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 18)); // NOI18N
        Address_Button_Accept.setText("Accept");
        Address_Button_Accept.setAlignmentY(0.0F);
        Address_Button_Accept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Address_Button_Accept.setFocusCycleRoot(true);
        Address_Button_Accept.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Address_Button_Accept.setIconTextGap(0);
        Address_Button_Accept.setMaximumSize(new java.awt.Dimension(90, 30));
        Address_Button_Accept.setMinimumSize(new java.awt.Dimension(90, 30));
        Address_Button_Accept.setPreferredSize(new java.awt.Dimension(90, 30));
        Address_Button_Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Address_Button_AcceptActionPerformed(evt);
            }
        });
        Address_MainPanel.add(Address_Button_Accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 110, 40));

        javax.swing.GroupLayout AddressLayout = new javax.swing.GroupLayout(Address.getContentPane());
        Address.getContentPane().setLayout(AddressLayout);
        AddressLayout.setHorizontalGroup(
            AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressLayout.createSequentialGroup()
                .addComponent(Address_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AddressLayout.setVerticalGroup(
            AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Address_MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(closeProgram());
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setFocusableWindowState(false);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cofirmExit_button_AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cofirmExit_button_AcceptActionPerformed
       //controlador.guardarPrograma();
       System.exit(0);
    }//GEN-LAST:event_cofirmExit_button_AcceptActionPerformed

    private void cofirmExit_button_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cofirmExit_button_CancelActionPerformed
        confirmExit.setVisible(false);
        LayerPn.setVisible(true);
    }//GEN-LAST:event_cofirmExit_button_CancelActionPerformed

    private void LogIn_TextField_UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogIn_TextField_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogIn_TextField_UserNameActionPerformed

    private void LogIn_Button_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogIn_Button_SignUpActionPerformed
        openFrameCloseFrame(SignUp,LogIn);
        cleanWindow(SignUp_MainPanel);
    }//GEN-LAST:event_LogIn_Button_SignUpActionPerformed

    private void LogIn_Button_AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogIn_Button_AcceptActionPerformed
        closeProgram();
    }//GEN-LAST:event_LogIn_Button_AcceptActionPerformed

    private void LogIn_Button_PasswordRecoveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogIn_Button_PasswordRecoveryActionPerformed
        openFrameCloseFrame(PasswordRecovery,LogIn);
        cleanWindow(PasswordRecovery_MainPanel);
    }//GEN-LAST:event_LogIn_Button_PasswordRecoveryActionPerformed

    private void SignUp_TextField_2ndSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_TextField_2ndSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_TextField_2ndSurnameActionPerformed

    private void SignUp_Button_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_Button_CancelActionPerformed
        openFrameCloseFrame(LogIn,SignUp);
        cleanWindow(LogIn_MainPanel);
    }//GEN-LAST:event_SignUp_Button_CancelActionPerformed

    private void SignUp_Button_AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_Button_AcceptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_Button_AcceptActionPerformed

    private void SignUp_TextField_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_TextField_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_TextField_UsernameActionPerformed

    private void SignUp_TextField_MiddleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_TextField_MiddleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_TextField_MiddleNameActionPerformed

    private void SignUp_TextField_1stSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_TextField_1stSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_TextField_1stSurnameActionPerformed

    private void SignUp_TextField_FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_TextField_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_TextField_FirstNameActionPerformed

    private void PasswordRecovery_TextField_UserName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordRecovery_TextField_UserName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordRecovery_TextField_UserName1ActionPerformed

    private void PasswordRecovery_Button_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordRecovery_Button_CancelActionPerformed
        openFrameCloseFrame(LogIn,PasswordRecovery);
        cleanWindow(LogIn_MainPanel);
    }//GEN-LAST:event_PasswordRecovery_Button_CancelActionPerformed

    private void PasswordRecovery_Button_AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordRecovery_Button_AcceptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordRecovery_Button_AcceptActionPerformed

    private void SignUp_FormattedTextField_BirthDate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_FormattedTextField_BirthDate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_FormattedTextField_BirthDate1ActionPerformed

    private void LogIn_Button_Accept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogIn_Button_Accept1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogIn_Button_Accept1ActionPerformed

    private void SignUp_Button_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_Button_AddressActionPerformed
        openFrameCloseFrame(Address,SignUp);
        cleanWindow(Address_MainPanel);
    }//GEN-LAST:event_SignUp_Button_AddressActionPerformed

    private void SignUp_Button_ChooseAPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_Button_ChooseAPhotoActionPerformed
        photoChooser.setVisible(true);
    }//GEN-LAST:event_SignUp_Button_ChooseAPhotoActionPerformed

    private void Address_Button_AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Address_Button_AcceptActionPerformed
        openFrameCloseFrame(SignUp,Address);
    }//GEN-LAST:event_Address_Button_AcceptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Address;
    private javax.swing.JButton Address_Button_Accept;
    private javax.swing.JComboBox<String> Address_ComboBox_Canton;
    private javax.swing.JComboBox<String> Address_ComboBox_Country;
    private javax.swing.JComboBox<String> Address_ComboBox_District;
    private javax.swing.JComboBox<String> Address_ComboBox_Province;
    private javax.swing.JPanel Address_Header;
    private javax.swing.JLabel Address_Label_Canton;
    private javax.swing.JLabel Address_Label_Country;
    private javax.swing.JLabel Address_Label_DetailedDescription;
    private javax.swing.JLabel Address_Label_District;
    private javax.swing.JLabel Address_Label_Province;
    private javax.swing.JLabel Address_Label_Tittle;
    private javax.swing.JLabel Address_Logo3;
    private javax.swing.JPanel Address_MainPanel;
    private javax.swing.JScrollPane Address_ScrollPane_DetailedDescriptionContainer;
    private javax.swing.JTextArea Address_TextArea_DetailedDescription;
    private javax.swing.JLayeredPane LayerPn;
    private javax.swing.JFrame LogIn;
    private javax.swing.JButton LogIn_Button_Accept;
    private javax.swing.JButton LogIn_Button_Accept1;
    private javax.swing.JButton LogIn_Button_PasswordRecovery;
    private javax.swing.JButton LogIn_Button_SignUp;
    private javax.swing.JPanel LogIn_Header;
    private javax.swing.JLabel LogIn_LabelPassword8;
    private javax.swing.JLabel LogIn_Label_Password;
    private javax.swing.JLabel LogIn_Label_PasswordRecovery;
    private javax.swing.JLabel LogIn_Label_UserName;
    private javax.swing.JLabel LogIn_Logo02;
    private javax.swing.JPanel LogIn_MainPanel;
    private javax.swing.JPasswordField LogIn_PasswordField_Password;
    private javax.swing.JTextField LogIn_TextField_UserName;
    private javax.swing.JLabel LogIn_logo01;
    private javax.swing.JFrame PasswordRecovery;
    private javax.swing.JButton PasswordRecovery_Button_Accept;
    private javax.swing.JButton PasswordRecovery_Button_Cancel;
    private javax.swing.JPanel PasswordRecovery_Header;
    private javax.swing.JLabel PasswordRecovery_Label_Tittle;
    private javax.swing.JLabel PasswordRecovery_Label_UserName;
    private javax.swing.JPanel PasswordRecovery_MainPanel;
    private javax.swing.JTextField PasswordRecovery_TextField_UserName1;
    private javax.swing.JLabel PasswordRecovery_logo2;
    private javax.swing.JFrame SignUp;
    private javax.swing.JButton SignUp_Button_Accept;
    private javax.swing.JButton SignUp_Button_Address;
    private javax.swing.JButton SignUp_Button_Cancel;
    private javax.swing.JButton SignUp_Button_ChooseAPhoto;
    private javax.swing.JFormattedTextField SignUp_FormattedTextField_BirthDate1;
    private javax.swing.JFormattedTextField SignUp_FormattedTextField_Email;
    private javax.swing.JFormattedTextField SignUp_FormattedTextField_Password;
    private javax.swing.JPanel SignUp_Header;
    private javax.swing.JLabel SignUp_Label_1stSurname;
    private javax.swing.JLabel SignUp_Label_2ndSurname;
    private javax.swing.JLabel SignUp_Label_BirthDate;
    private javax.swing.JLabel SignUp_Label_Direction;
    private javax.swing.JLabel SignUp_Label_Email;
    private javax.swing.JLabel SignUp_Label_FirstName;
    private javax.swing.JLabel SignUp_Label_MiddleName;
    private javax.swing.JLabel SignUp_Label_Password;
    private javax.swing.JLabel SignUp_Label_Tittle;
    private javax.swing.JLabel SignUp_Label_Username;
    private javax.swing.JLabel SignUp_Logo2;
    private javax.swing.JPanel SignUp_MainPanel;
    private javax.swing.JTextField SignUp_TextField_1stSurname;
    private javax.swing.JTextField SignUp_TextField_2ndSurname;
    private javax.swing.JTextField SignUp_TextField_FirstName;
    private javax.swing.JTextField SignUp_TextField_MiddleName;
    private javax.swing.JTextField SignUp_TextField_Username;
    private javax.swing.JButton cofirmExit_button_Accept;
    private javax.swing.JButton cofirmExit_button_Cancel;
    private javax.swing.JLabel cofirmExit_label_tittle;
    private javax.swing.JDialog confirmExit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JFrame mainWindow;
    private javax.swing.JFileChooser photoChooser;
    // End of variables declaration//GEN-END:variables
}
